-- Clear existing data and reset IDs
TRUNCATE TABLE loans, books, borrowers RESTART IDENTITY CASCADE;

-- Insert all 438 books from the Biblioteca CcAlv spreadsheet
INSERT INTO books (nome, categoria, numero_copias, autor) VALUES
('1984', 'Arte e Literatura', 1, 'George Orwell'),
('1808 - Como uma rainha louca, um príncipe medroso e uma corte corrupta enganaram Napoleão e mudaram a História de Portugal e do Brasil', 'História', 1, 'Laurentino Gomes'),
('1822 - Como um homem sábio, uma princesa triste e um escocês louco por dinheiro ajudaram D. Pedro a criar o Brasil - um país que tinha tudo para dar errado', 'História', 1, 'Laurentino Gomes'),
('1889 - Como um imperador cansado, um marechal vaidoso e um professor injustiçado contribuíram para o fim da Monarquia e a Proclamação da República no Brasil', 'História', 1, 'Laurentino Gomes'),
('25 minutos - A vida de Chiara Luce Badano', 'Biografia', 1, 'Franz Cariasco'),
('50 Anos em 5 - Meu caminho para Brasília Volume III', 'Biografia', 1, 'Juscelino Kubitschek'),
('9 ateus mudam de ônibus', 'Leitura espiritual', 2, 'José Ramón Ayllón'),
('A ação do espírito santo na alma', 'Leitura espiritual', 2, 'Alexis riaud'),
('A alegria de crer', 'Leitura espiritual', 1, 'Francisco Jose de almeida'),
('A arte de aproveitar as próprias faltas', 'Leitura espiritual', 1, 'Joseph Tissot'),
('A bondade', 'Leitura espiritual', 2, 'F. W. Faber'),
('A caminho de belém', 'Leitura espiritual', 2, 'Dorothy dohen'),
('A Cantiga dos pássaros e das serpentes', 'Arte e Literatura', 1, 'Suzanne Collins'),
('A cidade antiga', 'História', 1, 'Fustel de Coulanges'),
('A clara luz de Chiara Luce', 'Biografia', 1, 'Michele Zanzucchi'),
('A cruz de Cristo', 'Leitura espiritual', 4, 'Francisco Fernández-Carvajal'),
('A Escalada Política - Meu caminho para Brasília Volume II', 'Biografia', 1, 'Juscelino Kubitschek'),
('A escrava Isaura', 'Arte e Literatura', 1, 'Bernardo Guimarães'),
('A família', 'Leitura espiritual', 1, 'Alípio maia e castro'),
('A filosofia e seu Inverso', 'Filosofia', 2, 'Olavo De Carvalho'),
('A força do exemplo', 'Leitura espiritual', 2, 'Francico Faus'),
('A fraude da vinci', 'Leitura espiritual', 1, 'Mark shea e edward sri'),
('A hora dos ruminantes', 'Arte e Literatura', 1, 'José J.Veiga'),
('A hora sexta', 'Leitura espiritual', 2, 'Jose Miguel Pero Sanz'),
('A inocência do Padre', 'Arte e Literatura', 1, 'G.K Chersterton'),
('A inveja', 'Leitura espiritual', 2, 'Francisco Faus'),
('A Língua', 'Leitura espiritual', 3, 'Francisco Faus'),
('A luneta mágica', 'Arte e Literatura', 1, 'Joaquim Manuel de Macedo'),
('A luta pelo direito', 'Direito', 1, 'Rudolf Von Ihering'),
('A menina que roubava livros', 'Arte e Literatura', 1, 'Markus Zusak'),
('A metamorfose', 'Arte e Literatura', 1, 'Kafka'),
('A misericórdia divina', 'Leitura espiritual', 2, 'luiz fernando cintra'),
('A paciência', 'Leitura espiritual', 1, 'Francisco Faus'),
('A pequena via para Deus', 'Leitura espiritual', 1, 'St. Teresa do menino jesus'),
('A queda de Númenor', 'Arte e Literatura', 1, 'J.R.R Tolkien'),
('A República', 'Filosofia', 5, 'Platão'),
('A ressurreição e a esperança cristã', 'Leitura espiritual', 1, 'Francisco Faus'),
('A Revolução dos Bichos', 'Arte e Literatura', 1, 'George Orwell'),
('A sabedoria da cruz', 'Leitura espiritual', 3, 'Francisco Faus'),
('A sabedoria do Cristão', 'Leitura espiritual', 1, 'Leo J. Trese'),
('A semana I', 'Arte e Literatura', 1, 'Machado de Assis'),
('A semana II', 'Arte e Literatura', 1, 'Machado de Assis'),
('A sogra ( e a nora) ideal', 'Leitura espiritual', 1, 'Luz maria de la fuente'),
('A sós com Deus', 'Leitura espiritual', 2, 'Thomas more'),
('A última ao cadafalso', 'Leitura espiritual', 3, 'Gertrud von le fort'),
('A utopia', 'Arte e Literatura', 1, 'Thomas Morus'),
('A vitória da páscoa', 'Leitura espiritual', 2, 'Georges Chevrot'),
('A volta ao mundo em oitenta dias', 'Arte e Literatura', 1, 'Júlio Verne'),
('A vontade de poder', 'Leitura espiritual', 1, 'José Lino C. Nieto'),
('A voz da consciência', 'Leitura espiritual', 1, 'Francisco Faus'),
('Aborto e sociedade permissiva', 'Leitura espiritual', 1, 'Pedro-Juan Viladrich'),
('Adeus, China', 'Biografia', 1, 'Li Cunxin'),
('Airton Queiroz - Destino & Trajetória', 'Biografia', 1, 'Fernando Jorge'),
('Aléxia - Uma história de dor, coragem e alegria', 'Leitura espiritual', 1, 'Miguel Angel Monge'),
('Álgebra linear e suas aplicações', 'Matemática', 1, 'Gilbert Strang'),
('Amar a igreja', 'Leitura espiritual', 2, 'São josemaria escrivá'),
('amar o mundo apaixonadamente', 'Leitura espiritual', 1, 'são josemaria escrivá'),
('Amigos de Deus', 'Leitura espiritual', 1, 'são josemaria escrivá'),
('Análise das estruturas', 'Engenharia', 1, 'R. C. Hibbeler'),
('Antologia Poética', 'Arte e Literatura', 1, 'Fernando Pessoa'),
('Apocalipse', 'Leitura espiritual', 1, 'Geraldo morujão'),
('Apologia de Sócrates', 'Filosofia', 1, 'Platão'),
('Aristóteles em Nova Perspectiva', 'Filosofia', 1, 'Olavo De Carvalho'),
('Arte ou Desastre', 'Arte e Literatura', 1, 'Ângelo Monteiro'),
('As aventuras de Pinóquio - História de uma Marionete', 'Arte e Literatura', 1, 'Carlo Collodi'),
('As aventuras de Robson Crusoé', 'Arte e Literatura', 1, 'Daniel Defoe'),
('As boas mulheres da China', 'História', 1, 'Xinran'),
('As idades da vida', 'Leitura espiritual', 1, 'Romano Guardini'),
('As idades da vida', 'Leitura espiritual', 2, 'Romano Guardini'),
('Autenticidade e cia', 'Leitura espiritual', 2, 'Francisco Faus'),
('Automação Industrial e Sistemas de Manufatura', 'Engenharia', 1, 'Mikell P. Groover'),
('Balas de estalo & crítica', 'Arte e Literatura', 1, 'Machado de Assis'),
('Banquete', 'Filosofia', 1, 'Dante Alighieri'),
('Bernardette saulurano', 'Leitura espiritual', 1, 'Marcelle Auclair'),
('Bernardo de claraval', 'Leitura espiritual', 1, 'Daniel Rops'),
('Bons dias! & Notas Semanais', 'Arte e Literatura', 1, 'Machado de Assis'),
('Brás, Bexiga e Barra Funda e outros contos', 'Arte e Literatura', 1, 'Antônio de Alcântara Machado'),
('Brave New World', 'Arte e Literatura', 1, 'Aldous Huxley'),
('Breve História de Portugal', 'História', 1, 'A.H De Oliveira Marques'),
('Brisingr', 'Arte e Literatura', 1, 'Christopher Paolini'),
('Cantigas Populares', 'Arte e Literatura', 1, 'Juvenal Galeno'),
('Caritas in veritate', 'Leitura espiritual', 1, 'Bento xvi'),
('Carta dos amigos de cristo', 'Leitura espiritual', 1, 'Antonio gomez martinez'),
('Carta os jovens', 'Leitura espiritual', 2, 'João Paulo II'),
('Cartas dos amigos de cristo', 'Leitura espiritual', 2, 'Antonio gomez martinez'),
('Cartas perto do coração', 'Arte e Literatura', 1, 'Fernando Sabino e Clarice Lispector'),
('Cartas que você não lerá', 'Leitura espiritual', 3, 'Rogelio C. Ramos'),
('Catecismo breve', 'Leitura espiritual', 1, 'Enrique pelach'),
('Categorias', 'Filosofia', 1, 'Aristóteles'),
('Cem dias entre céu e mar', 'Arte e Literatura', 1, 'Amyr Klink'),
('Chatô - O Rei do Brasil', 'Biografia', 1, 'Fernando Morais'),
('Cidade de Água e Sal - Por uma antropologia do Litoral Norte e Nordeste sem cana e sem açúcar', 'História', 1, 'Paulo Linhares'),
('Ciencia e milagres', 'Leitura espiritual', 1, 'Jorge pimentel cintra'),
('Cisnes Selvagens - Três Filhas da China', 'Biografia', 1, 'José Luis Lira'),
('Código da Vida', 'Arte e Literatura', 1, 'Saulo Ramos'),
('Como aproveitar os defeitos alheios', 'Leitura espiritual', 2, 'Juan Marqués Suriñach'),
('Concerto de Cordas - Antologia Poética', 'Arte e Literatura', 1, 'Luiz Coronel'),
('Confissões', 'Biografia', 1, 'Santo Agostinho'),
('Confissões de um converso', 'Leitura espiritual', 2, 'Robert Hugh Benson'),
('Contos', 'Arte e Literatura', 1, 'Machado de Assis'),
('Contos de natal', 'Leitura espiritual', 1, 'Vários autores'),
('Contos Escolhidos', 'Arte e Literatura', 1, 'Moreira Campos'),
('Contos Escolhidos', 'Arte e Literatura', 1, 'Machado de Assis'),
('Controle Essencial 2a edição', 'Engenharia', 1, 'Paulo Maya'),
('Correspondência', 'Arte e Literatura', 1, 'Machado de Assis'),
('Criação do Ocidente - A religião e a Civilização Medieval', 'História', 1, 'Christopher Dawson'),
('Crisálidas, Falenas & Americanas', 'Arte e Literatura', 1, 'Machado de Assis'),
('Cristo e o nosso corpo', 'Leitura espiritual', 1, 'André Léonard'),
('Cristo e os apóstolos', 'Leitura espiritual', 2, 'Otto Hophan'),
('Crítica & Correspondência', 'Arte e Literatura', 1, 'Machado de Assis'),
('Crítica & Variedades', 'Arte e Literatura', 1, 'Machado de Assis'),
('Crônica Brasileira Contemporânea', 'Arte e Literatura', 1, 'Manuel da Costa Pinto'),
('Curso de Direito Constitucional - Para graduação e concursos públicos', 'Direito', 1, 'Paulo Roberto de Figueiredo Dantas'),
('Curso de Direito Processual Penal', 'Direito', 1, 'Sérgio Rebouças'),
('D. Leopoldina - Cartas de uma Imperatriz', 'Biografia', 1, 'Edson Arantes do Nascimento (Pelé)'),
('Damião o leproso', 'Leitura espiritual', 2, 'John Farrow'),
('Desvirando a página: A vida de Olavo Setubal', 'Biografia', 1, 'Juscelino Kubitschek'),
('Deus caritas est', 'Leitura espiritual', 1, 'Bento XVI'),
('Deus e os cientistas', 'Leitura espiritual', 2, 'Jorge pimentel cintra'),
('Deus é vermelho - A história secreta de como o cristianismo sobreviveu e floresceu na China comunista', 'História', 1, 'Liao Yiwu'),
('Dicionário de Mitologia Greco-Romana', 'História', 1, 'Victor Civita'),
('Dicionário Médico Andre', 'Medicina', 1, 'L. Manuila, A. Manuila, M, Nicoulin'),
('Direito da estética urbana - A cidade como arte coletiva', 'Direito', 1, 'Francisco das Chagas de Vasconcelos Neto'),
('Direito Tributário', 'Direito', 1, 'André Elali, Hugo de Brito Machado Segundo, Terence Trennepohl'),
('Dom Casmurro', 'Arte e Literatura', 1, 'Machado de Assis'),
('Dom Quixote De La Mancha - Volume I', 'Arte e Literatura', 1, 'Miguel de Cervantes'),
('Dom Quixote De La Mancha - Volume II', 'Arte e Literatura', 1, 'Miguel de Cervantes'),
('Dora del Hoyo', 'Leitura espiritual', 1, 'Javier Medina Bayo'),
('Doutor Fausto', 'Arte e Literatura', 1, 'Thomas Mann'),
('E = mc^2 - Uma biografia da equação que mudou o mundo e o que ela significa', 'Matemática', 1, 'David Bodanis'),
('Eldest', 'Arte e Literatura', 1, 'Christopher Paolini'),
('Elementos Finitos', 'Matemática', 1, 'Tirupathi R. Chandrupatla'),
('Engenharia de Controle Moderno', 'Engenharia', 1, 'Katsuhiko Ogata'),
('Ensaios sobre os deuses depressivos', 'Filosofia', 1, 'Seymour Glass'),
('Eragon', 'Arte e Literatura', 1, 'Christopher Paolini'),
('Escravidão Volume I - Do primeiro leilão de cativos em Portugal até a morte de Zumbi dos Palmares', 'História', 1, 'Laurentino Gomes'),
('Escritos Avulsos I', 'Arte e Literatura', 1, 'Machado de Assis'),
('Escritos avulsos II', 'Arte e Literatura', 1, 'Machado de Assis'),
('Escritos Avulsos III', 'Arte e Literatura', 1, 'Machado de Assis'),
('Estrela Cadente - As contradições e trapalhadas do PT', 'História', 1, 'Rodrigo Constantino'),
('Ética a Nicômaco', 'Filosofia', 1, 'Aristóteles'),
('Eurípedes - Medéia - Hipólito - As troianas', 'Arte e Literatura', 1, 'Mário da Gama Kury'),
('Evangelho de maria', 'Leitura espiritual', 4, 'Salvador M. Iglesias'),
('Evolucionismo mito e realidade', 'Leitura espiritual', 1, 'Jorge Pimentel Cintra'),
('Família em contos - Os Larletos', 'Arte e Literatura', 1, 'Ariovaldo Esteves Roggerio'),
('Fausto - Uma tragédia - Primeira Parte', 'Arte e Literatura', 1, 'Johann Wolfgang Von Goethe'),
('Fé e realidades humanas', 'Leitura espiritual', 2, 'j.j. Grinda'),
('Fé oração e ousadia', 'Leitura espiritual', 2, 'Papa Francisco'),
('Fedro', 'Filosofia', 1, 'Platão'),
('Ficções do Interlúdio', 'Arte e Literatura', 1, 'Fernando Pessoa'),
('Fidelidade', 'Leitura espiritual', 1, 'Javier abad gómez'),
('Figuras da Inteligência Brasileira', 'Biografia', 1, 'Miguel Reale'),
('Filhos informação sexual', 'Leitura espiritual', 1, 'Francisco Sequeira'),
('Filhos: quando educá-los', 'Leitura espiritual', 1, 'James B stenson'),
('Filhos: quanto educá-los', 'Leitura espiritual', 1, 'James B. Stenson'),
('Filipe Neri', 'Leitura espiritual', 1, 'Guilherme Sanches Ximenes'),
('Fogo Morto', 'Arte e Literatura', 1, 'José Lins do Rego'),
('Folhetins de Silvanus e A Machadada', 'Arte e Literatura', 1, 'Juvenal Galeno'),
('Fortaleza, História e Estórias - Memórias de uma cidade', 'História', 1, 'Narcélio Limaverde'),
('Franny and Zooey', 'Arte e Literatura', 1, 'J. D. Salinger'),
('Frustrações e paz', 'Leitura espiritual', 2, 'dorothy dohen'),
('Fundamentos da Matemática Elementar 6', 'Matemática', 1, 'Gelson Iezzi'),
('Fundamentos de Instrumentação', 'Engenharia', 1, 'Luis Antonio Aguirre'),
('Fundamentos de Matemática Elementar 1', 'Matemática', 2, 'Gelson Iezzi'),
('Fundamentos de Matemática Elementar 2', 'Matemática', 1, 'Gelson Iezzi'),
('Fundamentos de Matemática Elementar 3', 'Matemática', 1, 'Gelson Iezzi'),
('Fundamentos de Matemática Elementar 7', 'Matemática', 2, 'Gelson Iezzi'),
('Gastando tempo com os filhos', 'Leitura espiritual', 2, 'Mannoun chimelli'),
('Generosidade', 'Leitura espiritual', 2, 'pierre charles'),
('Generosidade', 'Leitura espiritual', 1, 'Pierre Charles'),
('Gente Pobre', 'Arte e Literatura', 1, 'Fiódor Dostoiévski'),
('Getúlio - De volta pela consagração popular ao suicídio', 'Biografia', 1, 'Dona Leopoldina'),
('Getúlio - Do governo provisório à ditadura do Estado Novo', 'Biografia', 1, 'Jung Chang'),
('Getúlio - Dos anos de formação à conquista do poder', 'Biografia', 1, 'Ignácio de Loyola Brandão'),
('Getúlio Vargas e sou seu tempo: um retrato com luz e sombra', 'Biografia', 1, 'Ronaldo Costa Couto'),
('Glória de maria', 'Leitura espiritual', 1, 'S. Afonso de ligório'),
('Grandes Esperanças', 'Arte e Literatura', 1, 'Charles Dickens'),
('Grandes Mentes - Bosch', 'Arte e Literatura', 2, 'Bosch'),
('Grandes Mentes - Botticelli', 'Arte e Literatura', 1, 'Botticelli'),
('Grandes Mentes - Cain Velázquez', 'Arte e Literatura', 1, 'Velázquez'),
('Grandes Mentes - Cézanne', 'Arte e Literatura', 1, 'Cézanne'),
('Grandes Mentes - Dalí', 'Arte e Literatura', 1, 'Dalí'),
('Grandes Mentes - Degas', 'Arte e Literatura', 1, 'Degas'),
('Grandes Mentes - Delacroix', 'Arte e Literatura', 1, 'Delacroix'),
('Grandes Mentes - Gauguin', 'Arte e Literatura', 1, 'Gauguin'),
('Grandes Mentes - Goya', 'Arte e Literatura', 1, 'Goya'),
('Grandes Mentes - Kandinsky', 'Arte e Literatura', 1, 'Kandinsky'),
('Grandes Mentes - Manet', 'Arte e Literatura', 1, 'Manet'),
('Grandes Mentes - Matisse', 'Arte e Literatura', 1, 'Matisse'),
('Grandes Mentes - Modigliani', 'Arte e Literatura', 1, 'Modigliani'),
('Grandes Mentes - Monet', 'Arte e Literatura', 1, 'Monet'),
('Grandes Mentes - Picasso', 'Arte e Literatura', 1, 'Picasso'),
('Grandes Mentes - Rembrandt', 'Arte e Literatura', 1, 'Rembrandt'),
('Grandes Mentes - Renoir', 'Arte e Literatura', 1, 'Renoir'),
('Grandes Mentes - Toulouse-Lautrec', 'Arte e Literatura', 1, 'Toulouse-Lautrec'),
('Grandes Mestres - Leonardo Da Vinci', 'Arte e Literatura', 1, 'Leonardo Da Vinci'),
('Grandes Mestres - Michelangelo', 'Arte e Literatura', 1, 'Michelangelo'),
('Grandes pastores', 'Leitura espiritual', 2, 'André Frossard'),
('Guia Politicamente Incorreto da América Latina', 'História', 1, 'Leandro Narloch'),
('Guia Politicamente Incorreto da Filosofia', 'Filosofia', 1, 'Luiz Felipe Pondé'),
('Há um outro mundo', 'Leitura espiritual', 1, 'André frossard'),
('Hagakure - O livro do samurai', 'Filosofia', 1, 'Yamamoto Tsunetomo'),
('Hamlet', 'Arte e Literatura', 1, 'William Shakespeare'),
('Henrique V', 'Arte e Literatura', 1, 'William Shakespeare'),
('Herança', 'Arte e Literatura', 1, 'Christopher Paolini'),
('Hércules', 'Arte e Literatura', 1, 'Menelaos Stephanides'),
('História de Quinze Dias', 'Arte e Literatura', 1, 'Machado de Assis'),
('História Geral da Civilização Brasileira - I. A época colonial 1. Do descobrimento à expansão territórial', 'História', 1, 'Sérgio Buarque de Holanda'),
('História Geral da Civilização Brasileira - III. O Brasil Republicano 4.Economia e Cultura', 'História', 1, 'Sérgio Buarque de Holanda'),
('História Geral da Civilização Brasileira I.A Época Colonial 2. Administração, Economia, Sociedade', 'História', 1, 'Sérgio Buarque de Holanda'),
('História Geral da Civilização Brasileira II. O Brasil Monárquico 1.O Processo de Emancipação', 'História', 1, 'Sérgio Buarque de Holanda'),
('História Geral da Civilização Brasileira II. O Brasil Monárquico 2. Dispersão e Unidade', 'História', 1, 'Sérgio Buarque de Holanda'),
('História Geral da Civilização Brasileira II. O Brasil Monárquico 3. Reações e Transações', 'História', 1, 'Sérgio Buarque de Holanda'),
('História Geral da Civilização Brasileira II. O Brasil Monárquico 4.Declínio e queda do império', 'História', 1, 'Sérgio Buarque de Holanda'),
('História Geral da Civilização Brasileira II. O Brasil Monárquico 5. Do império à República', 'História', 1, 'Sérgio Buarque de Holanda'),
('História Geral da Civilização Brasileira III. O Brasil Republicano 1. Estrutura de Poder e Economia', 'História', 1, 'Sérgio Buarque de Holanda'),
('Histórias da Meia Noite', 'Arte e Literatura', 1, 'Machado de Assis'),
('Histórias Extraordinárias', 'Arte e Literatura', 1, 'Edgar Allan Poe'),
('Histórias Sem Data', 'Arte e Literatura', 1, 'Machado de Assis'),
('Homilias sobre a eucaristia', 'Leitura espiritual', 1, 'São Josemaria Escrivá'),
('Igreja & Política', 'Leitura espiritual', 1, 'J. Miguel Ibañez Langlois'),
('Il Piccolo Principe', 'Arte e Literatura', 1, 'Antoine De Saint-Exupéry'),
('Ilíada', 'Arte e Literatura', 2, 'Homero'),
('Instituições de direito civil - Volume II - Teoria Geral das obrigações', 'Direito', 1, 'Caio Mário Da Silva Pereira'),
('Intimidade com Deus', 'Leitura espiritual', 1, ''),
('Iracema', 'Arte e Literatura', 1, 'José de Alencar'),
('Iracema Cinco Minutos', 'Arte e Literatura', 1, 'José de Alencar'),
('João crisóstomo', 'Leitura espiritual', 1, 'Félix Arrarás'),
('João crisóstomo vida e martírio', 'Leitura espiritual', 1, 'Felix Arrarás'),
('João Paulo I o papa do sorriso', 'Leitura espiritual', 3, 'Andrea tornielli e alexxandro zangrando'),
('Jorge Lacerda - Uma luminosa mensagem de cultura', 'Biografia', 1, 'Paulo Sertek'),
('Juscelino Kubitschek - Meu caminho para Brasília Volume I', 'Biografia', 2, 'Lira Neto'),
('Juventude para todas as idades', 'Leitura espiritual', 3, 'Rafael LLano Cifuentes'),
('Lágrimas de cristo lágrima dos homens', 'Leitura espiritual', 2, 'Francisco Faus'),
('Laudato SI', 'Leitura espiritual', 1, 'Papa Francisco'),
('Lógica jurídica', 'Direito', 1, 'Chaim Perelman'),
('Luciola - Diva - Senhora', 'Arte e Literatura', 1, 'José de Alencar'),
('Lumen Gentium', 'Leitura espiritual', 1, ''),
('Macbeth', 'Arte e Literatura', 1, 'William Shakespeare'),
('Mãe de Deus e nossa mãe', 'Leitura espiritual', 1, 'Antonio Orozco'),
('Manual de Economia - 5a edição', 'Economia', 1, 'Diva benevides pinho e Marco Antonio S. de Vasconcelos'),
('Maria a mãe de Jesús', 'Leitura espiritual', 2, 'francisco faus'),
('Matemática aplicada à economia e administração', 'Economia', 1, 'Louis Leithold'),
('Matemática para economistas', 'Economia', 1, 'Carl P. Simmon'),
('Medida por medida', 'Arte e Literatura', 1, 'William Shakespeare'),
('Meditações de ética moral', 'Filosofia', 1, 'Raimundo Bezerra Falcão'),
('Meditando o Rosário com João Paulo II', 'Leitura espiritual', 1, 'João Paulo II'),
('Memorial de Aires', 'Arte e Literatura', 1, 'Machado de Assis'),
('Memórias de um Sargento de Milícias', 'Arte e Literatura', 2, 'Manuel Antônio de Almeida'),
('Memórias Póstumas de Brás Cubas', 'Arte e Literatura', 1, 'Machado de Assis'),
('Memórias Póstumas de Brás Cubas - Cedic', 'Arte e Literatura', 1, 'Machado de Assis'),
('Memórias Póstumas de Brás Cubas - Série Bom Livro', 'Arte e Literatura', 1, 'Machado de Assis'),
('Mensagens de nossa senhora aparecida', 'Leitura espiritual', 2, 'Fávio sampaio de paiva'),
('Mestre de bom humor', 'Leitura espiritual', 1, 'jose luis soria'),
('Mestre Gil de Ham', 'Arte e Literatura', 1, 'J.R.R Tolkien'),
('Metamorfoses', 'Arte e Literatura', 1, 'Ovídio'),
('Meu Deus', 'Leitura espiritual', 1, 'Peter seewald'),
('Meu Pé de Laranja Lima', 'Arte e Literatura', 1, 'José Mauro de Vasconcelos'),
('Milagre em Joaseiro', 'Biografia', 1, 'Ralph Della Cava'),
('Minimanual compacto de matemática teoria e prática', 'Matemática', 1, 'Tânia Cristina Neto G. Viveiro'),
('Moral: A arte de viver', 'Leitura espiritual', 1, 'Juan Luis Lorda'),
('Museu do Prado - Madri', 'Arte e Literatura', 1, 'Daniela Tarabra'),
('Não tem preço', 'Leitura espiritual', 1, 'Alex jones'),
('Natal com maria', 'Leitura espiritual', 1, 'José carlos pereira'),
('Natal: reunião dos sorrisos', 'Leitura espiritual', 1, 'francisco faus'),
('National Gallery - Londres', 'Arte e Literatura', 1, 'Daniela Tarabra'),
('No Alpendre com Rachel', 'Biografia', 2, 'Lira Neto'),
('No inicio do novo milenio', 'Leitura espiritual', 1, 'João Paulo II'),
('no príncipio Deus criou', 'Leitura espiritual', 2, 'Pedro urbano lopez de meneses'),
('O poema a virgem', 'Leitura espiritual', 1, 'são jose de anchieta'),
('O adolescente rebeldia e evasão', 'Leitura espiritual', 1, 'Geraldo Castillo'),
('O alienista', 'Arte e Literatura', 1, 'Machado de Assis'),
('O Alienista', 'Arte e Literatura', 1, 'Machado de Assis'),
('O anticristo', 'Leitura espiritual', 2, 'Michele dolz paulo franciulli'),
('O auto da compadecida', 'Arte e Literatura', 1, 'Ariano Suassuna'),
('O caso Valter', 'Leitura espiritual', 2, 'Hugo de azevedo'),
('O Castelo', 'Arte e Literatura', 1, 'Franz Kafka'),
('O combate espiritual', 'Leitura espiritual', 1, 'Lorenzo Scupoli'),
('O Conde de Monte Cristo - Volume I', 'Arte e Literatura', 1, 'Alexandre Dumas'),
('O coração de Cristo', 'Leitura espiritual', 1, 'Jean Galot'),
('O Credo', 'Leitura espiritual', 2, 'Ronald Knox'),
('O cristão e a dor', 'Leitura espiritual', 2, 'Richard Graf'),
('O cura Dars', 'Leitura espiritual', 1, 'Henri Chéon'),
('O Dia de Curinga', 'Arte e Literatura', 1, 'Jostein Gaarder'),
('O diabo, hoje', 'Leitura espiritual', 1, 'Georges huber'),
('O dom de si', 'Leitura espiritual', 2, 'Joseph Schrijvers'),
('O espião do Vaticano', 'Biografia', 1, 'Walter J. Ciszek'),
('O essencial de JK', 'Biografia', 2, 'Lira Neto'),
('O evangelho no lar', 'Leitura espiritual', 1, 'Georges Chevrot'),
('O Expresso Berlim-Bagdá', 'História', 1, 'Sean McMeekin'),
('O fabuloso livro azul', 'Arte e Literatura', 1, 'Andrew Lang'),
('O fato extraordinário', 'Leitura espiritual', 3, 'Manuel García Morente'),
('O fundador do opus dei', 'Leitura espiritual', 1, 'andrés vazques de prada'),
('O grande amigo de Deus', 'Biografia', 1, 'Taylor Caldwell'),
('O Guarani', 'Arte e Literatura', 1, 'José de Alencar'),
('O Hobbit', 'Arte e Literatura', 2, 'J.R.R Tolkien'),
('O homem em oração', 'Leitura espiritual', 1, 'Bento XVI'),
('O Homem Eterno', 'Arte e Literatura', 1, 'G.K Chersterton'),
('O homem que calculava', 'Biografia', 1, 'Malba Tahan'),
('O jogral de nossa senhora', 'Leitura espiritual', 2, 'Michel zink'),
('O Leopardo', 'Arte e Literatura', 1, 'Lampedusa'),
('O livro da mitologia', 'História', 1, 'Philip Wilkinson'),
('O lobo do mar', 'Arte e Literatura', 1, 'Jack London'),
('O mágico de Oz', 'Arte e Literatura', 1, 'L. Frank Baum'),
('O mercador de Veneza', 'Arte e Literatura', 1, 'William Shakespeare'),
('O método clínico', 'Medicina', 1, 'Ricardo Rocha Bastos'),
('O meu anjo caminhará a tua frente', 'Leitura espiritual', 1, 'Georges Huber'),
('O milagre de calanda', 'Leitura espiritual', 2, 'Paulo Oriente Franciulli'),
('O mistério de guadalupe', 'Leitura espiritual', 2, 'Francisco Ansón'),
('O mistério do Deus-Homem', 'Leitura espiritual', 2, 'Jacques Leclercq'),
('O mistério do natal', 'Leitura espiritual', 3, 'são joão de ávila'),
('O mito do governo grátis', 'Economia', 1, 'Paulo Rabelllo de Castro'),
('O morro dos ventos uivantes', 'Arte e Literatura', 1, 'Emily Bronte'),
('O Mundo de Sofia', 'Arte e Literatura', 1, 'Jostein Gaarder'),
('O Padre Cícero por ele mesmo', 'Biografia', 1, 'Therezinha Stella Guimarães e Anne Dumoulin'),
('O pai nosso', 'Leitura espiritual', 1, 'São Cipriano'),
('O peregrino da fé - A história de Frei Damião', 'Biografia', 1, 'Ana Lígia Lira e Pe Gabriel Vila Verde'),
('O poder e a glória', 'Arte e Literatura', 1, 'Graham Greene'),
('O preço a pagar', 'Leitura espiritual', 1, 'Joseph Fadelle'),
('O presépio das crianças', 'Leitura espiritual', 2, 'Fávio sampaio de paiva'),
('O pudor', 'Leitura espiritual', 3, 'Ada Simoncini'),
('O purgatório', 'Leitura espiritual', 1, ''),
('O que são os evangelhos', 'Leitura espiritual', 1, 'Geraldo morujão'),
('O retrato de Dorian Gray', 'Arte e Literatura', 1, 'Oscar Wilde'),
('O retrato de Dorian Gray - editora hedra', 'Arte e Literatura', 1, 'Oscar Wilde'),
('O rosário de nossa senhora', 'Leitura espiritual', 2, 'Bartologo longo'),
('O Senhor dos Anéis - As Duas Torres', 'Arte e Literatura', 3, 'J.R.R Tolkien'),
('O Senhor dos Anéis - O Retorno do Rei', 'Arte e Literatura', 3, 'J.R.R Tolkien'),
('O Silmarillion', 'Arte e Literatura', 3, 'J.R.R Tolkien'),
('O último dia de um condenado à morte', 'Arte e Literatura', 1, 'Victor Hugo'),
('Obras selecionadas de Machado de Assis Vol 4', 'Arte e Literatura', 1, 'Machado de Assis'),
('Odisseia', 'Arte e Literatura', 1, 'Homero'),
('Olhar para maria', 'Leitura espiritual', 1, 'Antonio Orozco Delclos'),
('Omissões', 'Leitura espiritual', 1, 'luiz fernando cintra'),
('Orações', 'Filosofia', 1, 'Cícero'),
('Orar com salmos', 'Leitura espiritual', 3, 'luiz fernando cintra'),
('Orio da Consciência', 'Arte e Literatura', 1, 'Oliver Sacks'),
('Ortodoxia', 'Leitura espiritual', 1, 'Chesterton'),
('Os anjos', 'Leitura espiritual', 1, 'Pedro barreto celestino'),
('Os cantos', 'Arte e Literatura', 1, 'Ezra Pound'),
('Os filhos de húrin', 'Arte e Literatura', 1, 'J.R.R Tolkien'),
('Os livros das Virtudes', 'Arte e Literatura', 1, 'William J. Bennett'),
('Os melhores contos - Lima Barreto', 'Arte e Literatura', 1, 'Lima Barreto'),
('Os mortes', 'Arte e Literatura', 1, 'James Joyce'),
('Os pensadores - Pré- Socráticos', 'Filosofia', 2, 'José Cavalcante de Souza'),
('Os pensadores - Santo Agostinho', 'Filosofia', 1, 'Santo Agostinho'),
('Os pensadores - Tomás de Aquino', 'Filosofia', 1, 'Tomás de Aquino'),
('Os Santos, pedras de escândalo', 'Leitura espiritual', 3, 'José Miguel Cejas'),
('Os sertões', 'Arte e Literatura', 1, 'Euclides da Cunha'),
('os sinais sagrados', 'Leitura espiritual', 2, 'Romano guardini'),
('Padre Cícero - A sabedoria do conselheiro do sertão', 'Biografia', 1, 'Padre Cícero'),
('Páginas dificeis do evangelho', 'Leitura espiritual', 1, 'Estevão bettencourt O.S.B.'),
('Páginas espirituais', 'Leitura espiritual', 2, 'Padre antonio vieira'),
('Páginas Exumadas', 'Arte e Literatura', 1, 'Raimundo Girão'),
('Páginas Recolhidas', 'Arte e Literatura', 1, 'Machado de Assis'),
('Pais bem- sucedidos', 'Leitura espiritual', 1, 'James B. Tenson'),
('Palavras do papa bento XVI no brasil', 'Leitura espiritual', 1, 'Papa Bento XVI'),
('Papéis Avulsos I', 'Arte e Literatura', 1, 'Machado de Assis'),
('Papéis Avulsos II', 'Arte e Literatura', 1, 'Machado de Assis'),
('Peanuts Completo - 1950 a 1952', 'Arte e Literatura', 1, 'Charles M. Schulz'),
('Peanuts Completo - 1953 a 1954', 'Arte e Literatura', 1, 'Charles M. Schulz'),
('Peanuts Completo - 1955 a 1956', 'Arte e Literatura', 1, 'Charles M. Schulz'),
('Peanuts Completo - 1957 a 1958', 'Arte e Literatura', 1, 'Charles M. Schulz'),
('Peanuts Completo - 1959 a 1960', 'Arte e Literatura', 1, 'Charles M. Schulz'),
('Peanuts Completo - 1961 a 1962', 'Arte e Literatura', 1, 'Charles M. Schulz'),
('Pelas mãos de pascal', 'Leitura espiritual', 1, 'Tamiya Toguchi'),
('Pelé - minha vida em imagens', 'Biografia', 1, 'Erotilde Honório e Diego Moreno'),
('Pensar por conta própria', 'Leitura espiritual', 1, 'Enrique monasterio'),
('Pergunte ao Pó', 'Arte e Literatura', 1, 'John Fante'),
('Por que a alegria?', 'Leitura espiritual', 3, 'Pius-aimone reggio'),
('Por que ir à missa aos domingos?', 'Leitura espiritual', 2, 'Luiz Fernando cintra'),
('Por um novo feminismo', 'Leitura espiritual', 3, 'Sueli caramello uliano'),
('Provérbios e virtudes', 'Leitura espiritual', 2, 'Jose lino c. nieto'),
('Psicologia aberta', 'Leitura espiritual', 1, 'Johannes B. Torelló'),
('Quando é Deus quem pergunta', 'Leitura espiritual', 1, 'Milton Ferreroni Júnior'),
('Que há para além da morte', 'Leitura espiritual', 2, 'Edouard Clerc'),
('Quincas Borba', 'Arte e Literatura', 1, 'Machado de Assis'),
('Quincas Borba - Edição anotada, com biografia do autor panorama da vida cotidiana da época', 'Arte e Literatura', 1, 'Machado de Assis'),
('Razão e sensibilidade - Orgulho e Preconceito - Persuasão', 'Arte e Literatura', 1, 'Jane Austen'),
('Relatos de um peregrino russo', 'Leitura espiritual', 1, 'Jean Gauvain'),
('Retratos de família', 'Leitura espiritual', 2, 'Cristina moraes vojvodic'),
('Romeu e Julieta & Hamlet', 'Arte e Literatura', 1, 'William Shakespeare'),
('Rosarium virginis mariae', 'Leitura espiritual', 1, 'João Paulo II'),
('Sacramentum caritatis', 'Leitura espiritual', 2, 'Papa Bento XVI'),
('Santo rosário', 'Leitura espiritual', 2, 'São Josemaria escrivá'),
('São Bernardo', 'Arte e Literatura', 1, 'Graciliano Ramos'),
('São Tómas de Aquino e São Francisco de Assis', 'Biografia', 1, 'G.K Chersterton'),
('Seabiscuit - Uma lenda americana', 'Biografia', 1, 'Laura Hillenbrand'),
('Senhora', 'Arte e Literatura', 1, 'José de Alencar'),
('Sherlock Holmes - Volume 2', 'Arte e Literatura', 1, 'Arthur Conan Doyle'),
('Sherlock Holmes - Volume 3', 'Arte e Literatura', 1, 'Arthur Conan Doyle'),
('Sherlock Holmes - Volume 4', 'Arte e Literatura', 1, 'Arthur Conan Doyle'),
('Sobre a Ira', 'Filosofia', 1, 'Sêneca'),
('Sociologia', 'Filosofia', 1, 'Gilberto Freyre'),
('Sombras de Reis Barbudos', 'Arte e Literatura', 1, 'José J. Veiga'),
('Somos livres?', 'Leitura espiritual', 1, 'Comarc Burke'),
('Sonho de uma noite de verão', 'Arte e Literatura', 1, 'William Shakespeare'),
('Spe Salvi', 'Leitura espiritual', 1, 'Bento XVI'),
('Star Wars - Herdeiro do Império', 'Arte e Literatura', 1, 'Timothy Zahn'),
('Star Wars - Marcas da Guerra', 'Arte e Literatura', 1, 'Chuck Wendig'),
('Star Wars - O último comando', 'Arte e Literatura', 1, 'Timothy Zahn'),
('Star Wars- Ascensão da força sombria', 'Arte e Literatura', 1, 'Timothy Zahn'),
('sulco', 'Leitura espiritual', 1, 'são josemaria escrivá'),
('Teatro', 'Arte e Literatura', 1, 'Machado de Assis'),
('Tempo de Despertar', 'Arte e Literatura', 1, 'Oliver Sacks'),
('Teoria da Linguagem', 'Filosofia', 1, 'Karl Buhler'),
('Teoria da Norma Jurídica', 'Direito', 1, 'Norberto Bobbio'),
('Teresa de lisieux', 'Leitura espiritual', 3, 'Henri Chéon'),
('Terra dos Homens', 'Arte e Literatura', 1, 'Antoine De Saint-Exupéry'),
('Tesouros Perdidos', 'Arte e Literatura', 1, 'Rodrigo Fonseca'),
('The complete work of William Shakespeare', 'Arte e Literatura', 1, 'William Shakespeare'),
('The Little Prince', 'Arte e Literatura', 1, 'Antoine De Saint-Exupéry'),
('The Pickwick Papers', 'Arte e Literatura', 1, 'Charles Dickens'),
('The Picture of Dorian Gray', 'Arte e Literatura', 1, 'Oscar Wilde'),
('Tomates verdes fritos No café da parada do Apito', 'Arte e Literatura', 1, 'Fannie Flagg'),
('Torto Arado', 'Arte e Literatura', 1, 'Itamar Vieira Junior'),
('Tratado da Verdadeira Devoção à Santíssima Virgem Maria', 'Leitura espiritual', 1, 'São Luís Maria Grignion de Montfort'),
('Tratado de Direito Penal', 'Direito', 1, 'Cezar Roberto Bitencourt'),
('Tratado do inferno', 'Leitura espiritual', 1, 'Santa francisca romana'),
('Tremendas Trivialidades', 'Arte e Literatura', 2, 'G.K Chersterton'),
('Três peças escolhidas', 'Arte e Literatura', 1, 'Eduardo Campos'),
('Triste Fim de Policarpo Quaresma', 'Arte e Literatura', 1, 'Lima Barreto'),
('Triste Fim de Policarpo Quaresma - Texto Integral com Comentários', 'Arte e Literatura', 1, 'Lima Barreto'),
('Trovadores Cearenses', 'Arte e Literatura', 1, 'Cândida Galeno'),
('Um Diário Russo', 'Arte e Literatura', 1, 'John Steinbeck e Robert Capa'),
('Um jogador', 'Arte e Literatura', 1, 'Fiódor Dostoiévski'),
('Uma breve história da Filosofia', 'Filosofia', 1, 'Nigel Warburton'),
('Uma breve história do Brasil', 'História', 1, 'Mary Del Priore e Renato Venancio'),
('Uma breve História do Século XX', 'História', 1, 'Geoffrey Blainey'),
('Uma História dos povos de língua inglesa', 'História', 1, 'Winston S. Churchill'),
('Uma loucura razoável', 'Leitura espiritual', 4, 'Joaquín Garcia-Huidobro'),
('União Soviética, Junho de 1941 - Operação Barbarossa I: a Invasão da URSS', 'História', 1, 'Robert Kirchubel'),
('Várias Histórias', 'Arte e Literatura', 1, 'Machado de Assis'),
('Vibrações Mecânicas', 'Engenharia', 1, 'Singiresu Rao'),
('Vida e Morte de M.J. Gonzaga de Sá', 'Arte e Literatura', 1, 'Lima Barreto'),
('Vida eucarística', 'Leitura espiritual', 1, 'Jose Manuel Iglesias'),
('What''s Wrong With The World', 'Arte e Literatura', 1, 'G.K Chersterton');

-- Insert sample borrowers
INSERT INTO borrowers (name, email, phone) VALUES
('João Silva', 'joao@example.com', '85999999999'),
('Maria Santos', 'maria@example.com', '85988888888'),
('Pedro Costa', 'pedro@example.com', '85977777777');

-- Success message
SELECT COUNT(*) as total_books FROM books;
